version: "3"
services:
    server:
        build: ./server
        expose:
          - 4000
        ports:
          - 4000:4000
        command: npm start
    client:
        build: ./calculator
        expose:
          - 3000
        ports:
          - 3000:3000
        links:
          - server
        command: npm start
